version: '3'
services:
  auth:
    build:
      context: ./auth_service
      dockerfile: Dockerfile.auth
    ports:
      - "5002:5002"
    restart: always
    depends_on:
      - mongodb
  product:
    build:
      context: ./product_service
      dockerfile: Dockerfile.product
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - auth
      - product
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
